<?php declare(strict_types=1);
/*
 * This file is part of the Gabbro Project: https://github.com/Gabbro-PHP
 *
 * Copyright (c) 2025 Daniel Bergløv, License: MIT
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
 * THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
 * THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

namespace gabbro\routing;

use gabbro\http\msg\Request;
use gabbro\http\msg\Response;

/**
 * Defines the contract for a request router.
 *
 * A router examines an incoming {@see Request} and dispatches it to the
 * appropriate controller, producing a {@see Response}.
 *
 * Implementations decide:
 *  - How routes are registered and matched (path patterns, verbs, etc).
 *  - How controllers are resolved and invoked (callables, classes, etc).
 *  - What happens if no route matches (e.g. returning 404).
 *
 * Routers can be used standalone or as part of a middleware pipeline,
 * depending on the application design.
 */
interface Router {

    /**
     * Route the given request to a matching controller.
     *
     * Implementations must:
     *  - Inspect the request to determine which route (if any) matches.
     *  - Invoke the associated controller.
     *  - Return the resulting response.
     *
     * If no route matches, implementations should return a
     * {@see Response} indicating that the resource was not found.
     *
     * @param Request $request   The request to route.
     *
     * @return Response          The response generated by the matched controller,
     *                           or an error response if no route matches.
     */
    function process(Request $request): Response;
}

